---
- hosts: docker_hubs
  become: true
  remote_user: ansible
  become_method: su
  vars:
    ansible_become_pass: root
  roles:
  - install-docker
  - { 
      role: install-docker-hub,
      dockerhub_path: /dockerhub,
      dockerhub_data: data
    }