---
- hosts: teamcity_agents
  become: true
  remote_user: ansible
  become_method: su
  vars:
    ansible_become_pass: root
  roles:
  - install-docker
  
  - { 
      role: install-teamcity-agent,
      teamcity_agent_service: teamcity-agent,
      teamcity_agent_path: /teamcity/agent,
      teamcity_agent_name: "{{ ansible_hostname }}",
      teamcity_agent_server_url: "http://{{ groups.teamcity_servers[0] }}:8111"
    }
