---
- hosts: teamcity_servers
  become: true
  remote_user: ansible
  become_method: su
  vars:
    ansible_become_pass: root
  roles:
  - install-docker
  
  - { 
      role: install-postgresql,
      postgresql_service: teamcity-server,
      postgresql_path: /teamcity/database,
      postgresql_data: data,
      postgresql_database: teamcity-server,
      postgresql_username: teamcity-server,
      postgresql_password: teamcity-server 
    }

  - { 
      role: install-teamcity-server,
      teamcity_server_service: teamcity-server,
      teamcity_server_port: 8111,
      teamcity_server_path: /teamcity/server,
      teamcity_server_data: data,
      teamcity_server_logs: logs
    }