---
- hosts: "{{ otakushelter_hosts }}"
  gather_facts: false
  tasks:
  - name: Setting previous build number
    set_fact: 
      otakushelter_prev_build_number: "{{ otakushelter_build_number | int - 1 }}"

  - name: Stopping {{ otakushelter_container }} container
    docker_container:
      name: "{{ otakushelter_container }}"
      image: "{{ otakushelter_image }}:1.0.{{ otakushelter_prev_build_number }}"
      state: absent

  - name: Remove {{ otakushelter_image }}:1.0.{{ otakushelter_prev_build_number }} image
    docker_image:
      name: "{{ otakushelter_image }}"
      tag: "1.0.{{ otakushelter_prev_build_number }}"
      force: true
      state: absent

  - name: Start {{ otakushelter_container }} from {{ otakushelter_image }}:1.0.{{ otakushelter_build_number }} container
    docker_container:
      name: "{{ otakushelter_container }}"
      image: "{{ otakushelter_image }}:1.0.{{ otakushelter_build_number }}"
      ports: "127.0.0.1:{{ otakushelter_port }}:80"
      state: started
      env:
        OTAKUSHELTER:DATABASE:PASSWORD: "{{ otakushelter_database_password }}"