---
- hosts: "{{ otakushelter_hosts }}"
  gather_facts: false
  tasks:
  - name: Setting previous build number
    set_fact: 
      otakushelter_prev_build_number: "{{ otakushelter_build_number | int - 1 }}"

  - name: Stopping {{ otakushelter_container }} container
    docker_container:
      name: "{{ otakushelter_container }}"
      image: "{{ otakushelter_image }}:1.0.{{ otakushelter_prev_build_number }}"
      state: absent

  - name: Remove {{ otakushelter_image }}:1.0.{{ otakushelter_prev_build_number }} image
    docker_image:
      name: "{{ otakushelter_image }}"
      tag: "1.0.{{ otakushelter_prev_build_number }}"
      force: true
      state: absent

  - name: Start container {{ otakushelter_container }} from {{ otakushelter_image }}:1.0.{{ otakushelter_build_number }}
    docker_container:
      name: "{{ otakushelter_container }}"
      image: "{{ otakushelter_image }}:1.0.{{ otakushelter_build_number }}"
      ports: "127.0.0.1:{{ otakushelter_port }}:80"
      state: started
      env:
        OTAKUSHELTER:DATABASE:PASSWORD: "{{ otakushelter_database_password | default('') }}"
        OTAKUSHELTER:RABBITMQ:PASSWORD: "{{ otakushelter_rabbitmq_password | default('') }}"
        OTAKUSHELTER:SECRET: "{{ otakushelter_secret | default('') }}"

  - name: Configure nginx
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/sites-available/{{ otakushelter_nginx_config }}
    notify: Restart nginx

  - name: Enable {{ otakushelter_nginx_config }} config
    file:
      src: /etc/nginx/sites-available/{{ otakushelter_nginx_config }}
      dest: /etc/nginx/sites-enabled/{{ otakushelter_nginx_config }}
      state: link
    notify: Restart nginx

  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted